### ISSUE TITLE
Custom tables break db:migrate

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-schema#516]
This seems to be caused by https://github.com/ManageIQ/manageiq-schema/pull/504, cc @NickLaMuro 

When the database contains tables not in the schema, `db:migrate` can now fail in various ways..

---

I copied `metric_rollups_01` to `xmetric_rollups_01` as a backup. That caused...

```
$ be rake db:migrate
** override_gem("manageiq-ui-classic", :path=>"/home/himdel/manageiq-ui-classic") at /home/himdel/manageiq/bundler.d/Gemfile.dev.rb:8
** ManageIQ master, codename: Kasparov
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/home/himdel/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/home/himdel/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)
```

Specifically failing on..

```
** Execute db:schema:dump
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/home/himdel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/manageiq-schema-6e7d2e7b5c75/lib/manageiq/schema/schema_dumper.rb:100:in `determine_table_parent'
/home/himdel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/manageiq-schema-6e7d2e7b5c75/lib/manageiq/schema/schema_dumper.rb:91:in `track_miq_metric_table_inheritance'
/home/himdel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/manageiq-schema-6e7d2e7b5c75/lib/manageiq/schema/schema_dumper.rb:16:in `table'
/home/himdel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/schema_dumper.rb:93:in `block in tables'
...
/home/himdel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/manageiq-schema-6e7d2e7b5c75/lib/manageiq/schema/schema_dumper.rb:7:in `tables'
...
```

(with `table_name` being `xmetric_rollups_01`).

---

Just adding a custom table with nothing in it...

```sql
 create table aaa (id serial);
```

db:migrate fails with..

```
NoMethodError: undefined method `comment' for nil:NilClass
/home/himdel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/manageiq-schema-6e7d2e7b5c75/lib/manageiq/schema/schema_dumper.rb:22:in `add_id_column_comment'
/home/himdel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/manageiq-schema-6e7d2e7b5c75/lib/manageiq/schema/schema_dumper.rb:15:in `table'
```

---

(Dropping the offending tables fixes the issue)

**Comment by NickLaMuro** [comment]
> I copied `metric_rollups_01` to `xmetric_rollups_01` as a backup. That caused...

Definitely something that was not consider when doing this, since we are just doing a regexp match on the table name as the original guard for that method, but the fix should be pretty easy.

> Just adding a custom table with nothing in it...
> 
> ```ruby
> create table aaa (id serial);
> ```
>

I think this is a false positive, as it should be `create_table` (not `create table` with a space), so the error currently is about the variable `table` being `nil`.

**Comment by NickLaMuro** [comment]
https://github.com/ManageIQ/manageiq-schema/pull/517

**Comment by himdel** [comment]
> create table aaa (id serial);
> I think this is a false positive, as it should be create_table (not create table with a space), so the error currently is about the variable table being nil.

Sorry, it's not. That was SQL, not ruby.

**Comment by NickLaMuro** [comment]
Okay... well you basically are doing something that Rails would never do in the first place:

https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L214-L253

Since it always defines a `PRIMARY KEY` when generating a table.

* * *

But whatever... solved with the second commit in #517

**Comment by Fryguy** [comment]
Closed via #517
