### PR TITLE
Nil MiqDatabase#update_repo_name

### PR DESCRIPTION
**Pull request by bdunne**
When migrating from 0, resulted in:
```
MoveRepoDataFromDatabaseToSettings#up handles nil update_repo_name
Failure/Error: described_class.migrate(migration_direction)

NoMethodError:
  undefined method `split' for nil:NilClass
# ./db/migrate/20160913195129_move_repo_data_from_database_to_settings.rb:15:in `block in up'
# /home/bdunne/.gem/ruby/2.4.3/gems/activerecord-5.0.6/lib/active_record/migration.rb:815:in `block in say_with_time'
# /home/bdunne/.gem/ruby/2.4.3/gems/activerecord-5.0.6/lib/active_record/migration.rb:815:in `say_with_time'
# ./db/migrate/20160913195129_move_repo_data_from_database_to_settings.rb:14:in `up'
# /home/bdunne/.gem/ruby/2.4.3/gems/activerecord-5.0.6/lib/active_record/migration.rb:792:in `exec_migration'
# /home/bdunne/.gem/ruby/2.4.3/gems/activerecord-5.0.6/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
# /home/bdunne/.gem/ruby/2.4.3/gems/activerecord-5.0.6/lib/active_record/migration.rb:772:in `block in migrate'
# /home/bdunne/.gem/ruby/2.4.3/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
# /home/bdunne/.gem/ruby/2.4.3/gems/activerecord-5.0.6/lib/active_record/migration.rb:771:in `migrate'
# /home/bdunne/.gem/ruby/2.4.3/gems/activerecord-5.0.6/lib/active_record/migration.rb:601:in `migrate'
# ./spec/support/migration_helper.rb:71:in `migrate_under_test'
# ./spec/support/migration_helper.rb:35:in `block (2 levels) in migrate'
# ./spec/support/migration_helper.rb:83:in `suppress_migration_messages'
# ./spec/support/migration_helper.rb:35:in `block in migrate'
# ./spec/support/migration_helper.rb:57:in `clearing_caches'
# ./spec/support/migration_helper.rb:31:in `migrate'
# ./spec/migrations/20160913195129_move_repo_data_from_database_to_settings_spec.rb:44:in `block (3 levels) in <top (required)>'
# ./spec/support/migration_helper.rb:57:in `clearing_caches'
# ./spec/support/migration_helper.rb:13:in `block (2 levels) in migration_context'
```
Introduced in: https://github.com/ManageIQ/manageiq/pull/11304

### CODE REVIEW

**Comment by bdunne** [comment]
@miq-bot add_reviewer @Fryguy

**Comment by bdunne** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by Fryguy** [comment]
@simaishi This PR is a bug fix for a migration, so needs to be backported to gaprindashvili.
